development:
 adapter: postgresql
 encoding: unicode
 database: omw
 host: localhost
 username: nikomc0
 password:
 port: 5432

test:
 adapter: postgresql
 encoding: unicode
 database: test
 pool: 5
 host: localhost
 username: 
 password:
 port: 5432


production:
  <<: *default
  database: db/production.sqlite3